# Generated by Django 2.2.4 on 2020-02-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200224_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_id',
            field=models.CharField(default='060XUN5G', max_length=20, primary_key=True, serialize=False),
        ),
    ]
